"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _valores_hero from './valores-hero.bones.json'
import _valor_card from './valor-card.bones.json'
import _costumbres_hero from './costumbres-hero.bones.json'
import _costumbre_card from './costumbre-card.bones.json'
import _danzas_hero from './danzas-hero.bones.json'
import _danza_card from './danza-card.bones.json'
import _gastronomia_card from './gastronomia-card.bones.json'
import _relato_card from './relato-card.bones.json'
import _lugares_hero from './lugares-hero.bones.json'
import _lugar_card from './lugar-card.bones.json'

registerBones({
  "valores-hero": _valores_hero,
  "valor-card": _valor_card,
  "costumbres-hero": _costumbres_hero,
  "costumbre-card": _costumbre_card,
  "danzas-hero": _danzas_hero,
  "danza-card": _danza_card,
  "gastronomia-card": _gastronomia_card,
  "relato-card": _relato_card,
  "lugares-hero": _lugares_hero,
  "lugar-card": _lugar_card,
})
